version: '3.4'

services:
  hubee.notificationapp.api:
    container_name: hubee.notificationapp.api
    image: ${DOCKER_REGISTRY-}hubeenotificationappapi
    environment:
        - HUBEE_CONNECTION_STRING=
        - HUBEE_MJML_APPLICATION_ID=
        - HUBEE_MJML_PUBLIC_KEY=
        - HUBEE_MJML_SECRET_KEY=
        - HUBEE_NOTIFICATION_EMAIL_CREDENTIAL_USERNAME=
        - HUBEE_NOTIFICATION_EMAIL_CREDENTIAL_PASSWORD=
        - MESSAGEBROKER_HOSTNAME=
        - MESSAGEBROKER_PASSWORD=
        - MESSAGEBROKER_PORT=
        - MESSAGEBROKER_USERNAME=
        - SERVICEDISCOVERY_HOSTNAME=
        - SERVICEDISCOVERY_PORT=
    build:
      context: .
      dockerfile: src/Hubee.Notification.App/Dockerfile
networks:
  default:
    external:
      name: shared_infra